
import Footer from "@/components/Footer";
import "../../(all-routes)/globals.css";
import Navbar from "@/components/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
     
        <div className="mt-10">{children}
          </div>
        <Footer/>
      </body>
    </html>
  );
}
